name: Build&Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o dist/ responser.go & go build -o dist/ spider.go & go build -o dist/ storer.go & go build -o dist/ tasks.go
      run: ls
      run: ls ./dist

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./dist/*"
        commit: "main"
        tag: "test2"
        token: ${{ secrets.GITHUB_TOKEN }}
